export enum EnumWriteAnAnswer {
  //token
  SET_TOKEN = "SET_TOKEN", 
  DELETE_TOKEN = "DELETE_TOKEN",

  SET_USER = "SET_USER",
  DELETE_USER = "DELETE_USER",

  SET_COURSE = "SET_COURSE",
  DELETE_COURSE = "DELETE_COURSE",

  SET_HISTORY = "SET_HISTORY",
  DELETE_HISTORY = "DELETE_HISTORY"
}
